# Generated by Django 4.2.26 on 2026-02-21 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExportJob',
            fields=[
                ('export_job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('both', 'Both')], default='both', max_length=10)),
                ('output_folder', models.CharField(max_length=500)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataImportJob',
            fields=[
                ('import_job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('validated', 'Validated'), ('committing', 'Committing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('mode', models.CharField(choices=[('append', 'Append'), ('replace', 'Replace')], default='append', max_length=10)),
                ('input_folder', models.CharField(max_length=500)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSchemaVersion',
            fields=[
                ('schema_version_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module_version', models.CharField(max_length=50, unique=True)),
                ('registry_checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRowError',
            fields=[
                ('data_row_error_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model_label', models.CharField(max_length=200)),
                ('row_number', models.IntegerField()),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('error_code', models.CharField(max_length=50)),
                ('error_message', models.TextField()),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_errors', to='main_data_management.dataimportjob')),
            ],
            options={
                'ordering': ['import_job', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='DataJobFile',
            fields=[
                ('data_job_file_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_role', models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('manifest', 'Manifest'), ('error_report', 'Error Report')], max_length=20)),
                ('relative_path', models.CharField(max_length=500)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main_data_management.dataexportjob')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main_data_management.dataimportjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
