# Generated by Django 4.2.29 on 2026-03-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_data_management", "0002_alter_dataimportjob_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datajobfile",
            name="export_job",
        ),
        migrations.DeleteModel(
            name="DataExportJob",
        ),
    ]
